apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-certificate
spec:
  dnsNames:
  - '*.example.com'
  issuerRef:
    kind: Issuer
    name: civo
  secretName: wildcard-example-com-tls